export default {
  PRODUCTS: "PRODUCTS",
  ALL_CATEGORIES: "ALL_CATEGORIES",
  CATEGORIES: "CATEGORIES",
  SET_CATEGORY: "SET_CATEGORY",
  SET_SUBCATEGORY: "SET_SUBCATEGORY",
  SET_MAX_PRICE: "SET_MAX_PRICE",
  SET_MIN_PRICE: "SET_MIN_PRICE",
  SET_SIZE: "SET_SIZE",
  SET_TYPE: "SET_TYPE",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
  SET_SORTED_PRODUCTS: "SET_SORTED_PRODUCTS",
  SET_CART: "SET_CART",
  DELETE_CART: "DELETE_CART",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_SORT_PRODUCTS: "SET_SORT_PRODUCTS",
  CURRENT_PAGE: "CURRENT_PAGE"
};